# Generated by Django 2.0.7 on 2018-08-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180807_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='post',
            name='subtile',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
