# Generated by Django 2.0.7 on 2018-08-08 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_post_preview_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subtile',
            new_name='subtitle',
        ),
    ]
