# Generated by Django 2.0.7 on 2018-09-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='theme_picture',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
