# Generated by Django 2.0.7 on 2018-09-17 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20180917_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='theme_picture',
        ),
    ]
