# Generated by Django 2.2.3 on 2019-08-06 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '博文', 'verbose_name_plural': '博文'},
        ),
    ]
