# Generated by Django 2.2.3 on 2019-08-15 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190806_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-publish_time'], 'verbose_name': '博文', 'verbose_name_plural': '博文'},
        ),
    ]
