# Generated by Django 2.2.3 on 2019-08-22 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190821_2200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
